### ISSUE TITLE
核心 Filter 添加怪物类型的支持

### ISSUE THREAD

**Issue by Akiranya** [Nyaadanbou/wakame#10]
## 配置文件

```yaml
- type: item:entity
  entity: minecraft:zombie
- type: item:entity
  entity: mythicmobs:zombie_plus
```

这里的 `entity` 的值应该支持多个实体类型。一个现成的方案是采用 `EntityTypeHolder` 以支持多个实体类型。这一点在物品的生物击杀统计数据那块已经有相应的代码实现，我们应该复用现有的代码。

## 代码实现

[SchemaGenerationTrigger](https://github.com/Nyaadanbou/wakame/blob/main/wakame-plugin/src/main/kotlin/cc/mewcraft/wakame/item/schema/SchemaGenerationTrigger.kt) 需要支持怪物掉落这种上下文。对应的 `SchemaGenerationContext` 也需要记录怪物的信息。这其中可能还需要包含怪物的击杀者之类的信息。

## 待讨论

好像可以，但没想的那么简单。

因为物品并不是总是从怪物身上掉的，也就是这个条件它甚至有的时候根本“没用”。

对于没用的条件，要怎么定义它呢（返回 `true` 或 `false`）@GetsumiDango
