### ISSUE TITLE
ItemSlotGroup 没有正常生效

### ISSUE THREAD

**Issue by Akiranya** [Nyaadanbou/wakame#133]
该物品在指定的 custom_item_slot 槽位都无法生效

```yaml
item_type: bow
item_name: '133'
attributable: { }
slot:
  - custom:9
  - custom:10
  - custom:11
level: 0
rarity: 'rarity:common'
cells:
  buckets:
    a:
      core: core_a
  selectors:
    core_groups:
      core_a:
        pool_1:
          - type: attribute:movement_speed
            operation: multiply_base
            value: 1.0
            weight: 1

```
