### ISSUE TITLE
remove_components未生效

### ISSUE THREAD

**Issue by Flandreqwq** [Nyaadanbou/wakame#153]
```
item_type: iron_sword
remove_components:
  - attribute_modifiers
slot: vanilla:mainhand
item_name: '<rarity:style>青铜剑'
attack: {}
castable: {}
attributable: {}
kizamiable: {}
skillful: {}
damageable:
  damage: 0
  max_damage: 350
  disappear_when_broken: true
level: 0
rarity: rarity:common
cells:
  buckets:
    attack_damage:
      core: core_attack_damage
    attack_speed_level:
      core: core_attack_speed_level
  selectors:
    core_groups:
      core_attack_damage:
        pool_1:
          - type: attribute:attack_damage
            element: neutral
            lower: 5
            upper: 6
            weight: 495
      core_attack_speed_level:
        pool_1:
          - type: attribute:attack_speed_level
            value: 3
            weight: 495
```
