### ISSUE TITLE
资源包支持添加 font

### ISSUE THREAD

**Issue by Akiranya** [Nyaadanbou/wakame#185]
# 方案 1

## 原型

1. 所有 font 都直接添加到 wakame 命名空间下.
2. 目前只需要支持两种 font 实现: [BitMapFontProvider](https://github.com/unnamed/creative/blob/main/api/src/main/java/team/unnamed/creative/font/BitMapFontProvider.java) 和 [SpaceFontProvider](https://github.com/unnamed/creative/blob/main/api/src/main/java/team/unnamed/creative/font/SpaceFontProvider.java)

## 配置文件

新增一个 <data>/fonts/providers 配置文件夹.

里面是字体的配置文件 (对应资源包里 `<namespace>/font/<key>.json`), 文件内容如下:

```yaml
# BitMap 字体
- type: bitmap
  file: /path/to/png # 相对于 <data>/fonts/textures
  ascent: 19
  height: 256
  chars: ["\uac00"]
- type: bitmap
  file: /path/to/png  # 相对于 <data>/fonts/textures
  ascent: 19
  height: 256
  chars: ["\uac01"]

# Space 字体
- type: space
  advances:
    a: 1
    b: 2
    c: 3
```

# 方案 2

直接使用现在已经写好的资源包合并功能.
