### ISSUE TITLE
词条栏选择器支持继承全局实例

### ISSUE THREAD

**Issue by Akiranya** [Nyaadanbou/wakame#22]
## 初步方案
- ~~只有 Pool 支持继承, Group 不需要继承~~
- Group 和 Pool 均支持继承全局实例
- Group 下新增一个 Node `parent` 以指定继承全局的实例
- Pool 下新增一个 Node `parent` 以指定继承全局的实例

## 全局配置

新增以下全局配置文件:

### `random/core_groups.yml`
```yaml
global_group_id_1: <group>
global_group_id_2: <group>
```

### `random/curse_groups.yml`
```yaml
global_group_id_1: <group>
global_group_id_2: <group>
```

### `random/core_pools.yml`
```yaml
global_pool_id_1: <group>
global_pool_id_2: <group>
```

### `random/curse_pools.yml`
```yaml
global_pool_id_1: <group>
global_pool_id_2: <group>
```

## Group 的具体设计
Group 的配置文件:
```yaml
parent: <string: global id>
filters: <list: filters>
selects: <map: pools>
```

filters 不继承.

selects 会继承, 遵循规则:
- 如果 local 有就按照 local 的
- 如果 local 没有就按照 parent

default 不继承.

## Pool 的具体设计

Pool 的配置文件:
```yaml
parent: <string: global id>
sample: <int: amount of sample to pick>
replacement: <bool: whether it is sampling with replacement>
filters: <list: filters>
entries: <map: samples>
```

sample 不继承.

replacement 不继承.

filters 不继承.

entries 继承, 遵循规则:
- 如果 local 有就按照 local 的
- 如果 local 没有就按照 parent
