### ISSUE TITLE
错误的技能配置文件会导致玩家一直卡在当前的 SkillState 中

### ISSUE THREAD

**Issue by Akiranya** [Nyaadanbou/wakame#47]
这个是错误的配置文件，其中 step_distance 是无效的。

```YAML
displays:
  name: "冲刺"
  tooltips:
  - <dark_gray><i>注意刹车.

# 技能模板的 type
type: dash

# 每一 Tick 冲刺的速度
step_distance: 0.5

# 冲刺的时间
duration: 100

conditions:
  - type: mana
    mana: "player.max_mana() / 50"
    success_message:
      - type: sound
        name: "block.note_block.pling" # 必写, 可用: https://minecraft.wiki/w/Sounds.json#Java_Edition_values
        source: "master" # 可选, 默认: MASTER, 可用: https://minecraft.wiki/w/Sound#Categories
        volume: 1.0 # 可选, 默认: 0.0, 可用: 0 到 2147483647
        pitch: 1.0 # 可选, 默认: 0.0, 可用: -1 到 1
        seed: 233 # 可选, 默认: null, 可用: 整数
        emitter: self # 可选, 默认: 'recipient_location', 可用值: 'self', 'recipient_location'
    failure_message:
      - type: title
        title: "<red>萎了"
        subtitle: "a"
        fade_in: 10
        stay: 20
        fade_out: 10
```

由于技能的配置文件是懒加载，因此技能运行所需要的数据是在 tick 阶段才会去加载。也就是说，首次执行技能会在 tick 函数内去加载数据，等于说首次 tick 会进行一系列的 I/O 操作。

如果在这个阶段抛出异常，玩家会卡在 cast_point 这个阶段，导致玩家会持续写入无用的 SkillContext（从后台可以看出来）。
