### ISSUE TITLE
实现合并系统的原型

### ISSUE THREAD

**Issue by Akiranya** [Nyaadanbou/wakame#67]
## 概述

合并台用于将两个核心合并成为一个。

合并台的存在也是为了“弥补”物品词条栏中不允许出现两个一模一样的核心的基本规则。

对于玩家来说，合并台将两个核心合并成一个更强的核心，可以更高效的利用词条栏的空间。

### 流程

1. GUI内需要有2个输入框，1个输出框（输入框内的核心必须为相同属性，相同计算方式）
2. 输出框用 lore 写明这个输出的大概样子（详细的样子参考下面的输出占位符）
3. 玩家在放入物品后，输出框不显示最终结果，只显示一个属性样子（不显示结果意图在便于合并台做一些数值上的调整/随机）
4. 玩家取出输出框物品后则合并成功并花费金币

### 输出占位符

包含以下信息：
1. 数值合并的计算方式（直接由配置文件写死文字内容，不涉及任何实时计算）
2. 合并需要的具体花费

### 花费

花费需要的参数

- 核心的具体属性，以及计算方式。
- 核心的等级

合并的花费计算
- 无论合并什么属性, 首先计算这个费用, 记为 A:
  - A = `base`
- 对于合并的 *每个* 便携版核心来说, 计算合并该核心的花费, 记为 B:
  - B = `便携版核心等级 * core_level_modifier + core_merge_modifier * per_core`
- 总花费的计算为: `A + ΣB`

### 合成台配置文件

```yaml
# 合并工作台是否启用?
enabled: true
# 合并工作台的容器GUI的标题
title: "合并工作台: Foo"

# 合并工作台可以接受的最大物品等级
max_accepted_level: 10
# 合并工作台输出的核心可以拥有的*最大*合并次数
max_merge_count: 2

# 输出的核心的合并次数的计算规则如下
# 合并台输出核心的合并次数永远为 2 个输入核心的合并次数*之和*再加一
# 最后看和是否大于 max_merge_count，如果大于则不能合并，如果小于或等于则可以合并

# 属性数值合并的计算方式
# x 代表第一个属性的数值
# y 代表第二个属性的数值
sum_formula:
  add: "(x+y) * 0.8"
  multiply_base: "(x+y) * 0.8"
  multiply_total: "(x+y) * 0.8"

# 合并工作台的花费计算
cost:
  # 基础花费, 类似起步价
  base: 200
  # 每个定制核心的基础花费, 类似的士的每公里的费用
  per_core: 基于每个核心类型
  # 便携版核心(PortableCore)的等级的修饰系数
  core_level_modifier: 1  
  # 便携版核心(PortableCore)的合并次数的修饰系数
  core_merge_count_modifier: 1
  # 这一级的 key 写合并次数, value 写 double 类型
  core_merge_count_mapping:
    0: 1
    1: 1
    2: 1.5

# 该合并台支持合并的核心类型，（可引用）
accepted_cores:
  - type: attribute:attack_damage
    element: fire
    operation: add
    cost: 100
  - type: attribute:attack_damage
    element: fire
    operation: base
    cost: 500
  - type: attack_effect_chance
    operation: add
    cost: 500
```

### 核心配置文件

```yaml
# 针对核心类型限制最大的合成次数，如果没有写则按合成工作台操作
限定的核心:
  - cost: 100
    max_merge_count: 1
    match:
       type: attribute:attack_damage
       element: fire
       operation: add
```

### 规则

2. 合并台输出核心的等级永远取 2 个核心中的大值
3. 合并台输出核心的合并次数永远为 2 个输入核心的合并次数之和再加一
5. 可以限制一个核心参与合并的最大次数

## 便携式核心

1. 增加一个标识，允许玩家识别一个便携式核心是合并产生的，还是原生的
2. 标识需要显示该核心的合并次数
