### ISSUE TITLE
分解系统(工作台)原型概述

### ISSUE THREAD

**Issue by GetsumiDango** [Nyaadanbou/wakame#89]
## 概述 (待更新 11/29)

分解台用于将装备分解为若干个核心。(只有被允许的核心可被分解出来)

分解台的存在是为了“完善”玩家获取便携式核心的渠道。

对于玩家来说，将装备放入分解工作台，可以有能力去消费多余的装备，获取更多的锻造素材。

允许玩家能够较低消耗的获得到原来的核心。

### 流程

1. GUI内需要有若干个输入框，1个确认框 （如果需要批量分解则需要若干个输入框）
2. 确认框用 lore 写明这个输出的大概样子（详细的样子参考下面的输出占位符）
3. 玩家在准备放入物品时，分解台需要判定该物品能否在这个分解台分解 
4. 如果不可分解则无法放入输入框，如果可分解则可以放入输入框
5. 按下确认框后则消费花费并且通过邮箱给予玩家分解后的物品。（通过邮箱，则不需要判定玩家背包是否充足）

### 输出占位符

包含以下信息：
1. 分解需要的具体花费

### 花费

花费需要的参数

- 装备的等级
- 装备的稀有度
- 待分解的核心的稀有度
- 装备的定制次数
- 分解核心的数量

### 分解台配置文件

```yaml
# 分解工作台是否启用?
enabled: true
# 分解工作台的容器GUI的标题
title: "分解工作台: Foo"

# 分解工作台 
# 这里的GUI界面可以参考重造工作台

# 分解工作台的花费计算
cost:
  # 基础花费, 类似起步价
  base: 
    # 这一级的 key 写装备的生效栏位, value写基础花费，（如果物品有多个生效栏位，则从上到下应用第一个符合的参数）
  
rarity_modifiers:
    # 这一级的key写稀有度的 id, 值写 double 类型的修饰系数
    common: 1.0
    uncommon: 1.1
    rare: 1.1
    epic: 1.0
    ancient: 1.0
  # 物品的等级的修饰系数
  item_level_modifier: 1

# 该分解台支持分解的核心类型
accepted_cells:

```

### 规则

1. 分解台输出核心的等级永远取来源的装备等级
2. 分解台输出的核心无法被合并
~2. 分解台输出的 原生核心 的合并次数永远为 0~
~3. 分解台输出的 合并核心 的合并次数永远为 该核心重造时的合并次数~ 

## 便携式核心

1. 增加一个标识，允许玩家识别一个便携式核心是合并产生的，还是原生的
3. 标识需要显示该核心的合并次数
