### ISSUE TITLE
回收系统具体设计

### ISSUE THREAD

**Issue by GetsumiDango** [Nyaadanbou/wakame#90]
### 流程

1. GUI内需要有若干个输入框，1个确认框 
2. 确认框用 lore 写明出售大概能获得多少钱
3. 按下确认后，玩家获得金币。聊天框提示玩家大概多赚了多少（配置文件设定一个每个物品的基准价格）

### 回收

回收需要的参数

- 装备的等级
- 装备的稀有度
- 装备重造的次数（8.20号新加。一个补偿机制。目的是为了玩家投入资源在武器上，系统回收这种装备时能够让玩家稍微回血。需要在文档说明/新手教程告诉玩家这个机制。）
- 装备定制的次数（同上）
- 能够指定每个装备的基础值。(10.24日加。可能可以和回收台的基础花费做个替换，不用装备的生效栏位作为判断，直接写某件wakame物品的命名空间id。)

回收计算

如果为wakame装备
- 首先判定回收的 每个 装备，再计算这个费用, 记为 A:
  - A = `base `
- 对于回收的 每个 物品来说, 计算这个物品的费用, 记为 B:
  - B = `物品等级 * rarity_modifiers * （item_level * item_level_modifier） + （reroll * reroll_modifier） * （mod * mod_modifier） `
- 总收益的计算为: `ΣA + ΣB`

如果为原版物品
- 直接读取回收的物品配置文件

### 回收台配置文件

```yaml
# 回收台是否启用?
enabled: true
# 回收台的容器GUI的标题
title: "回收台: foo"

# 回收台的花费计算
cost:
  # 基础花费, 类似起步价
  base: 
    # 这一级的 key 写装备的命名空间, value写基础收益，（如果物品有多个生效栏位，则从上到下应用第一个符合的参数）
    armor:wooden_set/helmet: 200
  rarity_modifiers:
    # 这一级的key写稀有度的 id, 值写 double 类型的修饰系数
    common: 0.8
    uncommon: 1
    rare: 1.0
    epic: 1.0
    ancient: 1.0
  # 物品的等级的修饰系数
  item_level_modifier: 1
  # 物品的总重造次数的修饰系数
  reroll_modifier: 30
  # 物品的总定制次数的修饰系数
  mod_modifier: 200

```

### 回收配置文件

```yaml
# 原版物品
item: 
 type: minecraft: ore_iron
   base: 
     min: 10
     max: 10

```
